### ISSUE TITLE
/mnt/d/Documents/CS/OS/kernel-zig/build.zig:43:33: error: expected token 'Symbol', found '{'

### ISSUE THREAD

**Issue by glyh** [jzck/kernel-zig#4]
My zig version is 0.5.0. I also tried 0.6.0 and as expected is not compiling as well.

**Comment by glyh** [comment]
I see the commit message "towards 0.10" but this also doesn't build with zig 0.10
